### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by syberphunk** [welford/qurp#14]
pi@raspberrypi:~/halflife/qurp/WinQuake $ ./build.sh release_gl
- - - - - - - - - - - - - - -
Start Make
- - - - - - - - - - - - - - -
- - - - - - - - - - - - - - - - - -
Release GL Build :
        targets : /bin/glquake
        build dir : releasearm
        mount dir : /home/pi/halflife/qurp/WinQuake
- - - - - - - - - - - - - - - - - -
make -f make.rpi targets BUILDDIR=releasearm CFLAGS="-Dstricmp=strcasecmp -march=armv6 -mfpu=vfp -mfloat-abi=hard -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux  -DUSE_HALF_FLOATS=1 -mfp16-format=alternative -march=armv6 -mfpu=vfp -mfloat-abi=hard -O3 -ffast-math -funroll-loops -fomit-frame-pointer -fexpensive-optimizations  -DRELEASE_BUILD=1"
make[1]: Entering directory '/home/pi/halflife/qurp/WinQuake'
gcc -Dstricmp=strcasecmp -march=armv6 -mfpu=vfp -mfloat-abi=hard -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux  -DUSE_HALF_FLOATS=1 -mfp16-format=alternative -march=armv6 -mfpu=vfp -mfloat-abi=hard -O3 -ffast-math -funroll-loops -fomit-frame-pointer -fexpensive-optimizations  -DRELEASE_BUILD=1 -DGLQUAKE -DUSE_GLES  -o releasearm/glquake/platform.pi.o -c /home/pi/halflife/qurp/WinQuake/platform.pi.c
gcc -Dstricmp=strcasecmp -march=armv6 -mfpu=vfp -mfloat-abi=hard -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux  -DUSE_HALF_FLOATS=1 -mfp16-format=alternative -march=armv6 -mfpu=vfp -mfloat-abi=hard -O3 -ffast-math -funroll-loops -fomit-frame-pointer -fexpensive-optimizations  -DRELEASE_BUILD=1 -DGLQUAKE -DUSE_GLES  -o releasearm/glquake/modern_gles_port.o -c /home/pi/halflife/qurp/WinQuake/modern_gles_port.c
gcc -Dstricmp=strcasecmp -march=armv6 -mfpu=vfp -mfloat-abi=hard -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux  -DUSE_HALF_FLOATS=1 -mfp16-format=alternative -march=armv6 -mfpu=vfp -mfloat-abi=hard -O3 -ffast-math -funroll-loops -fomit-frame-pointer -fexpensive-optimizations  -DRELEASE_BUILD=1 -DGLQUAKE -DUSE_GLES  -o releasearm/glquake/shader_gles.o -c /home/pi/halflife/qurp/WinQuake/shader_gles.c
gcc -Dstricmp=strcasecmp -march=armv6 -mfpu=vfp -mfloat-abi=hard -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux  -DUSE_HALF_FLOATS=1 -mfp16-format=alternative -march=armv6 -mfpu=vfp -mfloat-abi=hard -O3 -ffast-math -funroll-loops -fomit-frame-pointer -fexpensive-optimizations  -DRELEASE_BUILD=1 -DGLQUAKE -DUSE_GLES  -o releasearm/glquake/transforms.o -c /home/pi/halflife/qurp/WinQuake/transforms.c
In file included from /usr/include/stdlib.h:42:0,
                 from /home/pi/halflife/qurp/WinQuake/shader_gles.c:4:
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:79:15: error: duplicate member ‘__w_retcode’
  unsigned int __w_retcode:8;
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:80:15: error: duplicate member ‘__w_coredump’
  unsigned int __w_coredump:1;
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:81:15: error: duplicate member ‘__w_termsig’
  unsigned int __w_termsig:7;
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:93:15: error: duplicate member ‘__w_stopsig’
  unsigned int __w_stopsig:8; /* Stopping signal.  */
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:94:15: error: duplicate member ‘__w_stopval’
  unsigned int __w_stopval:8; /* W_STOPPED if stopped.  */
               ^
In file included from /usr/include/stdlib.h:42:0,
                 from /home/pi/halflife/qurp/WinQuake/platform.pi.c:5:
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:79:15: error: duplicate member ‘__w_retcode’
  unsigned int __w_retcode:8;
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:80:15: error: duplicate member ‘__w_coredump’
  unsigned int __w_coredump:1;
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:81:15: error: duplicate member ‘__w_termsig’
  unsigned int __w_termsig:7;
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:93:15: error: duplicate member ‘__w_stopsig’
  unsigned int __w_stopsig:8; /* Stopping signal.  */
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:94:15: error: duplicate member ‘__w_stopval’
  unsigned int __w_stopval:8; /* W_STOPPED if stopped.  */
               ^
make.rpi:683: recipe for target 'releasearm/glquake/shader_gles.o' failed
make[1]: *** [releasearm/glquake/shader_gles.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /usr/include/stdlib.h:42:0,
                 from /home/pi/halflife/qurp/WinQuake/quakedef.h:46,
                 from /home/pi/halflife/qurp/WinQuake/transforms.c:3:
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:79:15: error: duplicate member ‘__w_retcode’
  unsigned int __w_retcode:8;
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:80:15: error: duplicate member ‘__w_coredump’
  unsigned int __w_coredump:1;
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:81:15: error: duplicate member ‘__w_termsig’
  unsigned int __w_termsig:7;
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:93:15: error: duplicate member ‘__w_stopsig’
  unsigned int __w_stopsig:8; /* Stopping signal.  */
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:94:15: error: duplicate member ‘__w_stopval’
  unsigned int __w_stopval:8; /* W_STOPPED if stopped.  */
               ^
In file included from /opt/vc/include/interface/vcos/vcos.h:118:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/bcm_host.h:50,
                 from /home/pi/halflife/qurp/WinQuake/platform.pi.c:6:
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h: In function ‘vcos_semaphore_wait’:
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:254:42: error: ‘errno’ undeclared (first use in this function)
    while ((ret = sem_wait(sem)) == -1 && errno == EINTR)
                                          ^
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:254:42: note: each undeclared identifier is reported only once for each function it appears in
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:254:51: error: ‘EINTR’ undeclared (first use in this function)
    while ((ret = sem_wait(sem)) == -1 && errno == EINTR)
                                                   ^
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h: In function ‘vcos_semaphore_trywait’:
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:263:45: error: ‘errno’ undeclared (first use in this function)
    while ((ret = sem_trywait(sem)) == -1 && errno == EINTR)
                                             ^
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:263:54: error: ‘EINTR’ undeclared (first use in this function)
    while ((ret = sem_trywait(sem)) == -1 && errno == EINTR)
                                                      ^
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:267:22: error: ‘EAGAIN’ undeclared (first use in this function)
    else if (errno == EAGAIN)
                      ^
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h: In function ‘vcos_semaphore_wait_timeout’:
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:311:14: error: ‘errno’ undeclared (first use in this function)
          if (errno == EINTR) {
              ^
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:311:23: error: ‘EINTR’ undeclared (first use in this function)
          if (errno == EINTR) {
                       ^
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:313:30: error: ‘ETIMEDOUT’ undeclared (first use in this function)
          } else if (errno == ETIMEDOUT) {
                              ^
In file included from /usr/include/stdlib.h:42:0,
                 from /home/pi/halflife/qurp/WinQuake/quakedef.h:46,
                 from /home/pi/halflife/qurp/WinQuake/quake_shaders.h:2,
                 from /home/pi/halflife/qurp/WinQuake/modern_gles_port.c:17:
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:79:15: error: duplicate member ‘__w_retcode’
  unsigned int __w_retcode:8;
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:80:15: error: duplicate member ‘__w_coredump’
  unsigned int __w_coredump:1;
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:81:15: error: duplicate member ‘__w_termsig’
  unsigned int __w_termsig:7;
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:93:15: error: duplicate member ‘__w_stopsig’
  unsigned int __w_stopsig:8; /* Stopping signal.  */
               ^
/usr/include/arm-linux-gnueabihf/bits/waitstatus.h:94:15: error: duplicate member ‘__w_stopval’
  unsigned int __w_stopval:8; /* W_STOPPED if stopped.  */
               ^
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h: In function ‘vcos_event_wait’:
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:593:50: error: ‘errno’ undeclared (first use in this function)
    while ((ret = sem_wait(&event->sem)) == -1 && errno == EINTR)
                                                  ^
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:593:59: error: ‘EINTR’ undeclared (first use in this function)
    while ((ret = sem_wait(&event->sem)) == -1 && errno == EINTR)
                                                           ^
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h: In function ‘vcos_event_try’:
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:603:53: error: ‘errno’ undeclared (first use in this function)
    while ((ret = sem_trywait(&event->sem)) == -1 && errno == EINTR)
                                                     ^
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:603:62: error: ‘EINTR’ undeclared (first use in this function)
    while ((ret = sem_trywait(&event->sem)) == -1 && errno == EINTR)
                                                              ^
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:606:30: error: ‘EAGAIN’ undeclared (first use in this function)
    if (ret == -1 && errno == EAGAIN)
                              ^
make.rpi:685: recipe for target 'releasearm/glquake/transforms.o' failed
make[1]: *** [releasearm/glquake/transforms.o] Error 1
make.rpi:689: recipe for target 'releasearm/glquake/platform.pi.o' failed
make[1]: *** [releasearm/glquake/platform.pi.o] Error 1
make.rpi:681: recipe for target 'releasearm/glquake/modern_gles_port.o' failed
make[1]: *** [releasearm/glquake/modern_gles_port.o] Error 1
make[1]: Leaving directory '/home/pi/halflife/qurp/WinQuake'
make.rpi:75: recipe for target 'release_gl' failed
make: *** [release_gl] Error 2

**Comment by welford** [comment]
Are you following the build instructions from the readme.md? https://github.com/welford/qurp/blob/master/README.md

If so what version of the Pi are you using?

**Comment by syberphunk** [comment]
Yes, Raspberry Pi 3.

**Comment by welford** [comment]
looks like very a similar issue is covered here: https://stackoverflow.com/questions/33769348/error-compiling-duplicate-member-on-header-endian-h Is any of this relevant to you?

I see that it's no longer Jessie but Stretch, I won't have time to check that this runs on a vanilla installation of raspbian Stretch for a few day - will try to see if this is a general issue asap.

**Comment by syberphunk** [comment]
Doesn't appear to be relevant. If endian.h was being included more than once, then perhaps something like 'pragma once' should be used? It's difficult to determine where the problem is exactly, searching online has suggested that something is linked in on the compiler line that shouldn't be, though it's difficult to determine what.

**Comment by syberphunk** [comment]
Faulty SDCard.
