### ISSUE TITLE
Compiling on Raspbian Stretch

### ISSUE THREAD

**Issue by syberphunk** [welford/qurp#15]
Pre-requisites to add to the readme: 
libgegl-dev 
libgles2-mesa-dev

Though I notice we're compiling for armv6, perhaps the code could detect when we're using a Pi 3 and compile for armv7 ?

**Comment by welford** [comment]
I do not have either of those packages installed and the game compiles/links/runs -on stretch too, i've now updated.

I can look into targeting arm7 on Pi3, but would be interested to know more about the prerequisites too.

**Comment by syberphunk** [comment]
It wouldn't compile for me as those packages were missing. It also fails to launch using the new OpenGL driver.

**Comment by welford** [comment]
My mistake, I was using dpkg before. 

They do show up with apt search, however from a clean flash of both raspbian stretch and raspbian stretch lite (from https://www.raspberrypi.org/downloads/raspbian/) these packages are pre-installed.  How are you setting up your OS?

**Comment by welford** [comment]
They also showed up from an upgrade of Jessie

**Comment by syberphunk** [comment]
Flashed an SDCard with the latest raspbian stretch from raspberrypi.org, booted. Cloned repo, ran build script. Build script said the .so files of the packages weren't installed, then had to install the packages, build worked.

**Comment by welford** [comment]
My Linux skills are weak :)

Those libraries do not need to be installed, the makefile needs to be updated from

-lEGL -lGLESv2

to 

-lbrcmEGL -lbrcmGLESv2

Presumably brcm is broadcom.

Without looking into it very much, I guess this change was made between Jessie and Stretch. I'll make the change for that soon (you can edit ./build.sh to make this change locally)

I'll take a look at targeting the correct architecture maybe this weekend.

**Comment by welford** [comment]
https://github.com/welford/qurp/commit/4b6b8c9dca90cd4a4fa82efd631b70f126f8c66e

fixed
