### ISSUE TITLE
Fast Quake SDL like retropie ?

### ISSUE THREAD

**Issue by spartrekus** [welford/qurp#17]
Hello,

I would like to ask if it would work without having to use the OPENGL library, and actually a bit like retropie does (retroarch lib). 

Would you think that dev could go a bit in this direction? Likely all directions, dev, go on superbe graphics, shadows, superbe magic effects,... but won't work on perfs. of a pi. 

SIncerely / best regards,

**Comment by welford** [comment]
Currently no, but my aim is for this to work without OpenGL, using the software rendering in the original quake.

Apologies for the late reply.
