### ISSUE TITLE
keyboard events

### ISSUE THREAD

**Issue by kramble** [welford/qurp#7]
I have a possible fix for the keyboard events propagating to the shell
ioctl (pState->kb_input0, EVIOCGRAB, (void*)1);
see https://github.com/kramble/qurp/blob/master/WinQuake/platform.pi.c#L244

Not quite sure of the calling convention, some examples pass a pointer to an int vis
int grab = 1;
ioctl (pState->kb_input0, EVIOCGRAB, &grab);
Which sort-of makes sense, but the one I've used does work.
... ah, just looked at the linux driver evdev.c - it just uses the arg pointer as a flag, so ignore this, I was right the first time.

Unfortunately this breaks Control-C (SIGINT) handling (it just does nothing). Sigh.

**Comment by welford** [comment]
i think we can live with ctrl+c not working on a Release build as there is another way to exit the game.

**Comment by welford** [comment]
i've added #define RELEASE_BUILD=1 to the build so we can distinguish between a release and debug build see make.rpi for the change. If you would rather add a different define to toggle ctrl+c functionality feel free to add it.

**Comment by kramble** [comment]
I'll close this now as it's all done.
The pull seems to have gone OK, I downloaded the .zip and rebuilt both release and debug and they work fine.
And I've re-sync'd my fork onto your master (using these instructions FYI http://superuser.com/questions/456145/how-can-i-resync-a-fork-from-original)
Best of luck with the project.
Mark

**Comment by welford** [comment]
Thanks for the help! It definitely feels much more complete with the sound and input properly done, probably shouldn't have dragged my feet for so long with it.

**Comment by welford** [comment]
if you spot any other issues (assuming you are playing the game at some point) please raise them.

**Comment by kramble** [comment]
Yep, will do. One thing that comes to mind is the rendering of the ground in the first base level e1m1, inside the main base (after crossing the bridge, enter base and turn right to where the pillar with the globe target is). Textures on ground are flickering oddly during motion.

Anyway, I'll see if I can work out why I'm very occasionally losing keyup events (it's like a stuck key until cancelled).
